# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
latex: false
dist: trusty


before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libnetcdf-dev 


after_success:
  - Rscript -e 'covr::codecov()'

r_binary_packages:
  - ncdf4
  
